accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="accounts/login.html",
            extra_context={"title": "Login", "form": LoginForm()},
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("tasks.urls", namespace="tasks")),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"


urlpatterns = [
    path("", views.home, name="home"),
    path("create_task/", views.create_task, name="create_task"),
    path("view_task/<int:id>/", views.view_task, name="task"),
    path("delete_task/<int:id>/", views.delete_task, name="delete_task"),
    path("update_task/<int:id>/", views.update_task, name="update_task")
]

tasks/models.py
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    due_date = models.DateTimeField()
    completed = models.BooleanField(default=False)

    class Meta:
        """Metadata options for the Task model."""

        managed = True

    def __str__(self) -> str:
        """Return the string representation of the task."""
        return self.title

tasks/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        """This is Task Form"""

        model = Task
        fields = ["title", "description", "due_date", "completed"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "due_date": forms.DateInput(
                attrs={"class": "form-control", "type": "date"}
            ),
            "completed": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from tasks.forms import TaskForm

from .models import Task


@login_required
def home(request):
    task_list = Task.objects.filter(user=request.user)
    return render(
        request, "tasks/index.html", {"title": "Home", "task_list": task_list}
    )


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect("tasks:home")
    else:
        form = TaskForm()

    return render(
        request,
        "tasks/create_task.html",
        {"form": form, "title": "Create Task"},
    )


@login_required
def view_task(request, id):
    task_details = Task.objects.get(id=id)
    return render(request, "tasks/task.html", {"title": "Task", "task": task_details})


@login_required
def delete_task(request, id):
    Task.objects.filter(id=id).delete()
    return redirect("tasks:home")


@login_required
def update_task(request, id):
    task = get_object_or_404(Task, id=id)
    if request.method == "POST":
        task_form = TaskForm(request.POST, instance=task)
        if task_form.is_valid():
            task_form.save()
            return redirect(reverse("tasks:task", args=(id,)))
    else:
        task_form = TaskForm(instance=task)

    return render(
        request,
        "tasks/update_task.html",
        {"title": "Update Task", "form": task_form, "task": task},
    )

templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tasks:home' %}">Tasks</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tasks:create_task' %}">Add New Task</a>
              </li>
              <form class="d-flex" action="{% url 'accounts:logout' %}">
                {% csrf_token %}
                <button class="nav-link" id="logout" type="submit" name="logout">Logout</a>
              </form>
              {% endif %}
              </ul>
          </div>
        </div>
      </nav>

  {% for message in messages %}
      <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <strong>Message: </strong> {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}

  <div class="container">
    {% block content %}

    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>
</html>

templates/tasks/create_task.html
{% extends "tasks/base.html" %}

{% block content %}

<div class="login-form-container">
    {% if form.errors %}
        <ul class="messages">
            {% for message in form.errors %}
                <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
   {% endif %}
   <form class="container" method="post" action="{% url 'tasks:create_task' %}">
        {% csrf_token %}
        <div class="form-group mb-4">
            <h2 class="form-title">{{ title }}</h2>
        </div>

        {% for field in form %}
            <div class="form-group mb-4">
                <label class="col-form-label">{{ field.label }}</label>
                 {{ field }}
                 {{ field.errors }}
            </div>
        {% endfor %}
        {% if form.errors and not form.non_field_errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
        {% endfor %}
        {% endif %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="d-grid gap-2 d-md-block">
            <button class="btn btn-primary" type="submit">Create</button>
        </div>
    </form>
</div>
{% endblock %}

templates/tasks/index.html
{% extends "tasks/base.html" %}

{% block content %}
    <h1>Task List</h1>

    {% for task in task_list %}
    <div class="card" style="width: 50rem;">
        <div class="card-body">
            <a href="{% url 'tasks:task' task.id %}" class="card-link"><h5 class="card-title">{{ task.title }}</h5></a>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ task.due_date }}</h6>
            <p class="card-text">Task status is {% if task.completed %} completed {% else %} in progress. {% endif %}</p>
        </div>
    </div>
    {% endfor %}
{% endblock %}

templates/tasks/task.html
{% extends "tasks/base.html" %}

{% block content %}

<h2>{{ task.title }}</h2>

<div class="card" style="width: 50rem;">
    <div class="card-body">
        <a href="{% url 'tasks:task' task.id %}" class="card-link"><h5 class="card-title">{{ task.title }}</h5></a>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ task.due_date }}</h6>
        <p class="card-text">{{ task.description }}</p>
        <p class="card-text">Task status is {% if task.completed %} completed {% else %} in progress. {% endif %}</p>
        <a href="{% url 'tasks:update_task' task.id %}" class="card-link">Edit task</a>
        <a href="{% url 'tasks:delete_task' task.id %}">Delete Task</a>
    </div>
</div>

{% endblock %}

templates/tasks/update_task.html
{% extends "tasks/base.html" %}

{% block content %}

<div class="login-form-container">
    {% if form.errors %}
        <ul class="messages">
            {% for message in form.errors %}
                <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
   {% endif %}
   <form class="container" method="post" action="{% url 'tasks:update_task' task.id %}">
        {% csrf_token %}
        <div class="form-group mb-4">
            <h2 class="form-title">{{ title }}</h2>
        </div>

        {% for field in form %}
            <div class="form-group mb-4">
                <label class="col-form-label">{{ field.label }}</label>
                 {{ field }}
                 {{ field.errors }}
            </div>
        {% endfor %}
        {% if form.errors and not form.non_field_errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
        {% endfor %}
        {% endif %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="d-grid gap-2 d-md-block">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock %}